### PR TITLE
Adds Uniffi bindings

### PR DESCRIPTION
**Pull request by dubadub**
Introduces extra feature to export UniFFI bindings.

### CODE REVIEW

**Comment by Zheoni** [comment]
I looked at the `Cargo.toml` file and added some notes.  Until the changes you are pulling from the `uniffi` are not published to `crates.io` this can't be merged into main. Maybe into a separate branch that you can pull instead of main to use the bindings.

I only had a quick glance at the code, the derive API from uniffi seems better! I will wait until the depencies are all from crates.io 😅 

Also, once this is merged the structs from the model we had to change a couple of months back can be restored again, right?

**Comment by Zheoni** [comment]
Another options which may be better is to create a new crate in the workspace and put the bindings there. Similar to how the playground works with wasm.

**Comment by dubadub** [comment]
Thanks for checking! Alright, I didn't know about unmarked changes, but it makes sense as you mentioned it. Yeah, we can restore structs back now as I don't use them directly.

**Comment by dubadub** [comment]
@Zheoni thanks for idea with the workspace, it made its much cleaner.

**Comment by Zheoni** [comment]
Yes, this way it looks much cleaner! And we can even merge when you think it's ready since it is a separate crate.

Also, remove `bindings/Cargo.lock`. Only 1 lock file per workspace.

**Pull request merged**
